---
# Ubuntu

docker_version: "docker-ce=18.06.1~ce~3-0~ubuntu"

docker_remove_packages:
  - docker
  - docker-engine
  - docker.io

docker_install_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

kubelet_version: "kubelet=1.11.6-00"
kubeadm_version: "kubeadm=1.11.6-00"
kubectl_version: "kubectl=1.11.6-00"
