---
- name: ask for reset confirmation
  pause:
    prompt: WARNING! This will undefine Kubernetes on this node. Enter "yes" to proceed.
  register: k8s_reset_confirm
  tags:
    - k8s-reset

- name: reset kubernetes with kubeadm and delete kubeinit log file
  become: yes
  block:
    - shell: kubeadm reset --force
    - file:
        state: absent
        path: /opt/kubeinit.log
  when: k8s_reset_confirm.user_input == "yes"
  tags:
    - k8s-reset
