---
- name: define Ubuntu docker repository
  become: yes
  block:
    - name: define docker repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: define Ubuntu docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
  when: ansible_distribution == 'Ubuntu'
  tags:
    - docker

