---
- name: remove firewalld
  become: yes
  yum:
    name: "firewalld"
    state: absent
  tags:
    - docker

- name: define CentOS docker repository
  become: yes
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'CentOS'
  tags:
    - docker
